# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c617b424ccf89dc01e0c08517e345978fcb04eeff9d27f4a490a6e71959ea06af77590543d78d29c7bc666180007163f2dd98500df82eec3f7227ce79c2265a

test:
  secret_key_base: 17f5fa017b9a856c2228d01281e527dbb8295390cc466dc2d702fdd737510690e83ce9473e375281e78b19d2893d0365c60ea148834006fefa63264caba3a5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
